spring:
  application:
    name: api

  jackson:
    time-zone: America/Sao_Paulo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/barbershop
    username: root
    password: root

    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  error:
    include-stacktrace: never

ohana:
  security:
    token:
      secret: ${JWT_SIGN:k3Y$eCuRe1!nG@1g!N^eS3cReT123456}

